/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { StencilButtonType, StencilButtonVariant } from "./types/ui";
export { StencilButtonType, StencilButtonVariant } from "./types/ui";
export namespace Components {
    interface StencilButton {
        "adb": string;
        /**
          * required for accessibility
          * @default label
         */
        "ariaLabel": string;
        /**
          * disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Button label
         */
        "label": string;
        /**
          * type
          * @default buttons
         */
        "type": StencilButtonType;
        /**
          * theming variant
         */
        "variant": StencilButtonVariant;
    }
}
declare global {
    interface HTMLStencilButtonElement extends Components.StencilButton, HTMLStencilElement {
    }
    var HTMLStencilButtonElement: {
        prototype: HTMLStencilButtonElement;
        new (): HTMLStencilButtonElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-button": HTMLStencilButtonElement;
    }
}
declare namespace LocalJSX {
    interface StencilButton {
        "adb"?: string;
        /**
          * required for accessibility
          * @default label
         */
        "ariaLabel"?: string;
        /**
          * disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Button label
         */
        "label"?: string;
        /**
          * type
          * @default buttons
         */
        "type"?: StencilButtonType;
        /**
          * theming variant
         */
        "variant"?: StencilButtonVariant;
    }
    interface IntrinsicElements {
        "stencil-button": StencilButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-button": LocalJSX.StencilButton & JSXBase.HTMLAttributes<HTMLStencilButtonElement>;
        }
    }
}
